// <auto-generated />
using System;
using AssessmentService.Persistance.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssessmentService.Persistance.Migrations
{
    [DbContext(typeof(AssessmentDbContext))]
    [Migration("20251219101721_mig_001")]
    partial class mig_001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssessmentService.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsychologyTestId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PsychologyTestQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTestQuestionId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.MBTIQuestions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MBTIResultAnswersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MBTIResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MBTIResultAnswersId");

                    b.HasIndex("MBTIResultId");

                    b.ToTable("MBTIQuestions");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.MBTIResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MBTIResults");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.MBTIResultAnswers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MBTIResultAnswers");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTestAssignmentsIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonalityTraitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScoringDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityTraitId");

                    b.ToTable("PersonalityTestItems");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonalityTestItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Response")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityTestItemId");

                    b.ToTable("PersonalityTestResponses");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AgreeablenessScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("CandidatesIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ConscientiousnessScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExtraversionScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NeuroticismScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("OpennessScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalityTestResults");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalityTraits");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTestAssignmentsIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PsychologyTests");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestInterpretation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MinScore")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid?>("PersonalityTestResultsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PsychologyTestId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PsychologyTestResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityTestResultsId");

                    b.HasIndex("PsychologyTestId");

                    b.HasIndex("PsychologyTestResultId");

                    b.ToTable("PsychologyTestInterpretation");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologyTestId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ScoringWeight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTestId");

                    b.ToTable("PsychologyTestQuestions");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologyTestId")
                        .HasColumnType("int");

                    b.Property<Guid>("PsychologyTestQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TestResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTestId");

                    b.HasIndex("PsychologyTestQuestionId");

                    b.HasIndex("TestResultId");

                    b.ToTable("PsychologyTestResponses");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResponseAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PsychologyTestId")
                        .HasColumnType("int");

                    b.Property<Guid>("PsychologyTestQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PsychologyTestResultAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTestId");

                    b.HasIndex("PsychologyTestQuestionId");

                    b.HasIndex("PsychologyTestResultAnswerId");

                    b.ToTable("PsychologyTestResponseAnswers");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologyTestId")
                        .HasColumnType("int");

                    b.Property<string>("ResultData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologyTestId");

                    b.ToTable("PsychologyTestResults");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResultAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ResultData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PsychologyTestResultAnswers");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTestQuestion", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("PsychologyTestQuestionId");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.MBTIQuestions", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.MBTIResultAnswers", null)
                        .WithMany("MBTIQuestions")
                        .HasForeignKey("MBTIResultAnswersId");

                    b.HasOne("AssessmentService.Domain.Entities.MBTIResult", "MBTIResult")
                        .WithMany("MBTIQuestions")
                        .HasForeignKey("MBTIResultId");

                    b.Navigation("MBTIResult");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestItem", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PersonalityTrait", "PersonalityTrait")
                        .WithMany("PersonalityTestItems")
                        .HasForeignKey("PersonalityTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalityTrait");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestResponse", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PersonalityTestItem", "PersonalityTestItem")
                        .WithMany("PersonalityTestResponses")
                        .HasForeignKey("PersonalityTestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalityTestItem");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestInterpretation", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PersonalityTestResults", null)
                        .WithMany("Interpretation")
                        .HasForeignKey("PersonalityTestResultsId");

                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTest", null)
                        .WithMany("Interpretation")
                        .HasForeignKey("PsychologyTestId");

                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTestResult", "PsychologyTestResult")
                        .WithMany("Interpretation")
                        .HasForeignKey("PsychologyTestResultId");

                    b.Navigation("PsychologyTestResult");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestQuestion", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTest", "PsychologyTest")
                        .WithMany("PsychologyTestQuestions")
                        .HasForeignKey("PsychologyTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychologyTest");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResponse", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTest", "PsychologyTest")
                        .WithMany("PsychologyTestResponses")
                        .HasForeignKey("PsychologyTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTestQuestion", "PsychologyTestQuestion")
                        .WithMany("PsychologyTestResponses")
                        .HasForeignKey("PsychologyTestQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTestResult", "TestResult")
                        .WithMany("Responses")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PsychologyTest");

                    b.Navigation("PsychologyTestQuestion");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResponseAnswer", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTest", null)
                        .WithMany("PsychologyTestResponseAnswers")
                        .HasForeignKey("PsychologyTestId");

                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTestQuestion", "PsychologyTestQuestion")
                        .WithMany()
                        .HasForeignKey("PsychologyTestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTestResultAnswer", null)
                        .WithMany("Responses")
                        .HasForeignKey("PsychologyTestResultAnswerId");

                    b.Navigation("PsychologyTestQuestion");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResult", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.PsychologyTest", "PsychologyTest")
                        .WithMany("PsychologyTestResults")
                        .HasForeignKey("PsychologyTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychologyTest");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.MBTIResult", b =>
                {
                    b.Navigation("MBTIQuestions");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.MBTIResultAnswers", b =>
                {
                    b.Navigation("MBTIQuestions");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestItem", b =>
                {
                    b.Navigation("PersonalityTestResponses");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTestResults", b =>
                {
                    b.Navigation("Interpretation");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PersonalityTrait", b =>
                {
                    b.Navigation("PersonalityTestItems");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTest", b =>
                {
                    b.Navigation("Interpretation");

                    b.Navigation("PsychologyTestQuestions");

                    b.Navigation("PsychologyTestResponseAnswers");

                    b.Navigation("PsychologyTestResponses");

                    b.Navigation("PsychologyTestResults");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestQuestion", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("PsychologyTestResponses");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResult", b =>
                {
                    b.Navigation("Interpretation");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.PsychologyTestResultAnswer", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
